### ISSUE TITLE
插入硬盘之后提示未注册。

### ISSUE THREAD

**Issue by yckyos261** [DoubleLabyrinth/TuxeraNTFS-keygen#2]
断网的情况下插入也是未注册，但是注册码处显示已经注册了。

**Comment by DoubleLabyrinth** [comment]
可以截个图吗

**Comment by yckyos261** [comment]
![image](https://user-images.githubusercontent.com/3714381/42665543-a46842fa-8672-11e8-9874-b9d7e6fff16a.png)
![image](https://user-images.githubusercontent.com/3714381/42665550-ad1240ae-8672-11e8-9fd3-9f4cd231dbe4.png)

**Comment by yckyos261** [comment]
系统是10.13.4

**Comment by DoubleLabyrinth** [comment]
我已经更新了readme和代码，请卸载掉原来的tuxera，并删除原先的keygen、patcher和tuxera_key.bin，然后重新装好tuxera并根据新readme操作

**Comment by yckyos261** [comment]
测试了一下，可以正常使用了
